# permissions for end users to edit shims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: shim-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtime-class-manager
    app.kubernetes.io/part-of: runtime-class-manager
    app.kubernetes.io/managed-by: kustomize
  name: shim-editor-role
rules:
- apiGroups:
  - runtime.spinkube.dev
  resources:
  - shims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.spinkube.dev
  resources:
  - shims/status
  verbs:
  - get
