apiVersion: runtime.spinkube.dev/v1alpha1 
kind: Shim
metadata:
  name: spin-v2
  labels:
    app.kubernetes.io/name: spin-v2
    app.kubernetes.io/instance: spin-v2
    app.kubernetes.io/part-of: runtime-class-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: runtime-class-manager
spec:
  nodeSelector:
    spin: "true"

  fetchStrategy:
    type: anonymousHttp
    anonHttp:
      location: "https://github.com/spinkube/containerd-shim-spin/releases/download/v0.15.1/containerd-shim-spin-v2-linux-aarch64.tar.gz"

  runtimeClass:
    # Note: this name is used by the Spin Operator project as its default:
    # https://github.com/spinkube/spin-operator/blob/main/config/samples/spin-shim-executor.yaml
    name: wasmtime-spin-v2
    handler: spin-v2

  rolloutStrategy:
    type: recreate
